import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import Nav from "../components/Nav";
import NavLink from "../components/NavLink";
import styles from "../styles/Home.module.css";
import { AnimatePresence, AnimateSharedLayout, motion } from "framer-motion";

const Home: NextPage = () => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <AnimateSharedLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.main layout>
        <motion.div className={styles.background}>
          <div className={styles["page-grid"]}>
            <div className={styles["side-a"]}>
              <h1 className={styles.h1}>Lyrical Wallpaper</h1>
              <h3 className={styles.h2}>
                The modern way to listen to organize your favorite lyrics.
              </h3>
              <div className={styles["join-today"]}>JOIN TODAY</div>
            </div>
            <AnimatePresence>
              {isOpen && (
                <motion.div
                  layout
                  initial={{ opacity: 0, x: -100 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0 }}
                >
                  <Nav>
                    <NavLink text="Artist" />
                    <NavLink text="About" />
                  </Nav>
                </motion.div>
              )}
            </AnimatePresence>
            <motion.span
              onClick={() => {
                setIsOpen(!isOpen);
              }}
              layout
              className={`material-icons ${styles.icon}`}
            >
              menu
            </motion.span>
          </div>
        </motion.div>
      </motion.main>
    </AnimateSharedLayout>
  );
};

export default Home;
